### ISSUE TITLE
Error: Route "/[...all]" used `params.all`. `params` should be awaited before using its properties. 

### ISSUE THREAD

**Issue by Patolord** [openstatusHQ/nextjs-dynamic-breadcrumb#1]
Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

When updating to nextjs 15 and react 19, i get this error.
Not sure how to fix it.

**Comment by thibaultleouay** [comment]
@Patolord  thanks for reporting I'm going to upgrade it to latest next !

**Comment by thibaultleouay** [comment]
@Patolord  It's have fixed :) 

Feel free to open a new issue if you have others issues :)

**Comment by Patolord** [comment]
Thank you very much! :)
